server:
  port: 1000
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.dodannie
spring:
  datasource:
    druid:
      url: jdbc:mysql://106.54.141.54:3306/blog?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
      username: root
      password: Dod_Annie@921116
      driver-class-name: com.mysql.jdbc.Driver
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 10000
      testOnBorrow: true
      testOnReturn: false
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
  tengxun:
    accessKey: AKIDREoGXYaHuPima7gEuQx3uiGgkbqpNKhw
    secretKey: 8XheMUM1PYpqxtISN3UuEI4ey04xf9Ob
    bucket: ap-nanjing
    bucketName: dodannie-1300549060
    path: https://dodannie-1300549060.cos.ap-nanjing.myqcloud.com
    qianzui: blog
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 200MB
